// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pim_project.proto

package com.elca.vn.proto.model;

public interface PimProjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.elca.vn.proto.model.PimProject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 projectNumber = 2;</code>
   * @return The projectNumber.
   */
  int getProjectNumber();

  /**
   * <code>string projectName = 3;</code>
   * @return The projectName.
   */
  java.lang.String getProjectName();
  /**
   * <code>string projectName = 3;</code>
   * @return The bytes for projectName.
   */
  com.google.protobuf.ByteString
      getProjectNameBytes();

  /**
   * <code>string customer = 4;</code>
   * @return The customer.
   */
  java.lang.String getCustomer();
  /**
   * <code>string customer = 4;</code>
   * @return The bytes for customer.
   */
  com.google.protobuf.ByteString
      getCustomerBytes();

  /**
   * <code>int64 groupID = 5;</code>
   * @return The groupID.
   */
  long getGroupID();

  /**
   * <code>repeated int64 memberVISAs = 6;</code>
   * @return A list containing the memberVISAs.
   */
  java.util.List<java.lang.Long> getMemberVISAsList();
  /**
   * <code>repeated int64 memberVISAs = 6;</code>
   * @return The count of memberVISAs.
   */
  int getMemberVISAsCount();
  /**
   * <code>repeated int64 memberVISAs = 6;</code>
   * @param index The index of the element to return.
   * @return The memberVISAs at the given index.
   */
  long getMemberVISAs(int index);

  /**
   * <code>.com.elca.vn.proto.model.Status status = 7;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.com.elca.vn.proto.model.Status status = 7;</code>
   * @return The status.
   */
  Status getStatus();

  /**
   * <code>.google.protobuf.Timestamp startDate = 8;</code>
   * @return Whether the startDate field is set.
   */
  boolean hasStartDate();
  /**
   * <code>.google.protobuf.Timestamp startDate = 8;</code>
   * @return The startDate.
   */
  com.google.protobuf.Timestamp getStartDate();
  /**
   * <code>.google.protobuf.Timestamp startDate = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp endDate = 9;</code>
   * @return Whether the endDate field is set.
   */
  boolean hasEndDate();
  /**
   * <code>.google.protobuf.Timestamp endDate = 9;</code>
   * @return The endDate.
   */
  com.google.protobuf.Timestamp getEndDate();
  /**
   * <code>.google.protobuf.Timestamp endDate = 9;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder();

  /**
   * <code>.com.elca.vn.proto.model.ProcessingStatus processingStatus = 10;</code>
   * @return The enum numeric value on the wire for processingStatus.
   */
  int getProcessingStatusValue();
  /**
   * <code>.com.elca.vn.proto.model.ProcessingStatus processingStatus = 10;</code>
   * @return The processingStatus.
   */
  ProcessingStatus getProcessingStatus();
}
