// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pim_project.proto

package com.elca.vn.proto.model;

/**
 * Protobuf type {@code com.elca.vn.proto.model.PimProject}
 */
public  final class PimProject extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.elca.vn.proto.model.PimProject)
    PimProjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PimProject.newBuilder() to construct.
  private PimProject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PimProject() {
    projectName_ = "";
    customer_ = "";
    memberVISAs_ = emptyLongList();
    status_ = 0;
    processingStatus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PimProject();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PimProject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 16: {

            projectNumber_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            projectName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            customer_ = s;
            break;
          }
          case 40: {

            groupID_ = input.readInt64();
            break;
          }
          case 48: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              memberVISAs_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            memberVISAs_.addLong(input.readInt64());
            break;
          }
          case 50: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              memberVISAs_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              memberVISAs_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 66: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (startDate_ != null) {
              subBuilder = startDate_.toBuilder();
            }
            startDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startDate_);
              startDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (endDate_ != null) {
              subBuilder = endDate_.toBuilder();
            }
            endDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endDate_);
              endDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            processingStatus_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        memberVISAs_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProjectProto.internal_static_com_elca_vn_model_PimProject_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProjectProto.internal_static_com_elca_vn_model_PimProject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PimProject.class, PimProject.Builder.class);
  }

  public static final int PROJECTNUMBER_FIELD_NUMBER = 2;
  private int projectNumber_;
  /**
   * <code>int32 projectNumber = 2;</code>
   * @return The projectNumber.
   */
  public int getProjectNumber() {
    return projectNumber_;
  }

  public static final int PROJECTNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object projectName_;
  /**
   * <code>string projectName = 3;</code>
   * @return The projectName.
   */
  public java.lang.String getProjectName() {
    java.lang.Object ref = projectName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projectName_ = s;
      return s;
    }
  }
  /**
   * <code>string projectName = 3;</code>
   * @return The bytes for projectName.
   */
  public com.google.protobuf.ByteString
      getProjectNameBytes() {
    java.lang.Object ref = projectName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMER_FIELD_NUMBER = 4;
  private volatile java.lang.Object customer_;
  /**
   * <code>string customer = 4;</code>
   * @return The customer.
   */
  public java.lang.String getCustomer() {
    java.lang.Object ref = customer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      customer_ = s;
      return s;
    }
  }
  /**
   * <code>string customer = 4;</code>
   * @return The bytes for customer.
   */
  public com.google.protobuf.ByteString
      getCustomerBytes() {
    java.lang.Object ref = customer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUPID_FIELD_NUMBER = 5;
  private long groupID_;
  /**
   * <code>int64 groupID = 5;</code>
   * @return The groupID.
   */
  public long getGroupID() {
    return groupID_;
  }

  public static final int MEMBERVISAS_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.LongList memberVISAs_;
  /**
   * <code>repeated int64 memberVISAs = 6;</code>
   * @return A list containing the memberVISAs.
   */
  public java.util.List<java.lang.Long>
      getMemberVISAsList() {
    return memberVISAs_;
  }
  /**
   * <code>repeated int64 memberVISAs = 6;</code>
   * @return The count of memberVISAs.
   */
  public int getMemberVISAsCount() {
    return memberVISAs_.size();
  }
  /**
   * <code>repeated int64 memberVISAs = 6;</code>
   * @param index The index of the element to return.
   * @return The memberVISAs at the given index.
   */
  public long getMemberVISAs(int index) {
    return memberVISAs_.getLong(index);
  }
  private int memberVISAsMemoizedSerializedSize = -1;

  public static final int STATUS_FIELD_NUMBER = 7;
  private int status_;
  /**
   * <code>.com.elca.vn.proto.model.Status status = 7;</code>
   * @return The enum numeric value on the wire for status.
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.elca.vn.proto.model.Status status = 7;</code>
   * @return The status.
   */
  public Status getStatus() {
    @SuppressWarnings("deprecation")
    Status result = Status.valueOf(status_);
    return result == null ? Status.UNRECOGNIZED : result;
  }

  public static final int STARTDATE_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp startDate_;
  /**
   * <code>.google.protobuf.Timestamp startDate = 8;</code>
   * @return Whether the startDate field is set.
   */
  public boolean hasStartDate() {
    return startDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp startDate = 8;</code>
   * @return The startDate.
   */
  public com.google.protobuf.Timestamp getStartDate() {
    return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp startDate = 8;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
    return getStartDate();
  }

  public static final int ENDDATE_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp endDate_;
  /**
   * <code>.google.protobuf.Timestamp endDate = 9;</code>
   * @return Whether the endDate field is set.
   */
  public boolean hasEndDate() {
    return endDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp endDate = 9;</code>
   * @return The endDate.
   */
  public com.google.protobuf.Timestamp getEndDate() {
    return endDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp endDate = 9;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder() {
    return getEndDate();
  }

  public static final int PROCESSINGSTATUS_FIELD_NUMBER = 10;
  private int processingStatus_;
  /**
   * <code>.com.elca.vn.proto.model.ProcessingStatus processingStatus = 10;</code>
   * @return The enum numeric value on the wire for processingStatus.
   */
  public int getProcessingStatusValue() {
    return processingStatus_;
  }
  /**
   * <code>.com.elca.vn.proto.model.ProcessingStatus processingStatus = 10;</code>
   * @return The processingStatus.
   */
  public ProcessingStatus getProcessingStatus() {
    @SuppressWarnings("deprecation")
    ProcessingStatus result = ProcessingStatus.valueOf(processingStatus_);
    return result == null ? ProcessingStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (projectNumber_ != 0) {
      output.writeInt32(2, projectNumber_);
    }
    if (!getProjectNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, projectName_);
    }
    if (!getCustomerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, customer_);
    }
    if (groupID_ != 0L) {
      output.writeInt64(5, groupID_);
    }
    if (getMemberVISAsList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(memberVISAsMemoizedSerializedSize);
    }
    for (int i = 0; i < memberVISAs_.size(); i++) {
      output.writeInt64NoTag(memberVISAs_.getLong(i));
    }
    if (status_ != Status.NEW.getNumber()) {
      output.writeEnum(7, status_);
    }
    if (startDate_ != null) {
      output.writeMessage(8, getStartDate());
    }
    if (endDate_ != null) {
      output.writeMessage(9, getEndDate());
    }
    if (processingStatus_ != ProcessingStatus.INSERT.getNumber()) {
      output.writeEnum(10, processingStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (projectNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, projectNumber_);
    }
    if (!getProjectNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, projectName_);
    }
    if (!getCustomerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, customer_);
    }
    if (groupID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, groupID_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < memberVISAs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(memberVISAs_.getLong(i));
      }
      size += dataSize;
      if (!getMemberVISAsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      memberVISAsMemoizedSerializedSize = dataSize;
    }
    if (status_ != Status.NEW.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, status_);
    }
    if (startDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getStartDate());
    }
    if (endDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getEndDate());
    }
    if (processingStatus_ != ProcessingStatus.INSERT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, processingStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PimProject)) {
      return super.equals(obj);
    }
    PimProject other = (PimProject) obj;

    if (getProjectNumber()
        != other.getProjectNumber()) return false;
    if (!getProjectName()
        .equals(other.getProjectName())) return false;
    if (!getCustomer()
        .equals(other.getCustomer())) return false;
    if (getGroupID()
        != other.getGroupID()) return false;
    if (!getMemberVISAsList()
        .equals(other.getMemberVISAsList())) return false;
    if (status_ != other.status_) return false;
    if (hasStartDate() != other.hasStartDate()) return false;
    if (hasStartDate()) {
      if (!getStartDate()
          .equals(other.getStartDate())) return false;
    }
    if (hasEndDate() != other.hasEndDate()) return false;
    if (hasEndDate()) {
      if (!getEndDate()
          .equals(other.getEndDate())) return false;
    }
    if (processingStatus_ != other.processingStatus_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROJECTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getProjectNumber();
    hash = (37 * hash) + PROJECTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProjectName().hashCode();
    hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
    hash = (53 * hash) + getCustomer().hashCode();
    hash = (37 * hash) + GROUPID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGroupID());
    if (getMemberVISAsCount() > 0) {
      hash = (37 * hash) + MEMBERVISAS_FIELD_NUMBER;
      hash = (53 * hash) + getMemberVISAsList().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasStartDate()) {
      hash = (37 * hash) + STARTDATE_FIELD_NUMBER;
      hash = (53 * hash) + getStartDate().hashCode();
    }
    if (hasEndDate()) {
      hash = (37 * hash) + ENDDATE_FIELD_NUMBER;
      hash = (53 * hash) + getEndDate().hashCode();
    }
    hash = (37 * hash) + PROCESSINGSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + processingStatus_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PimProject parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PimProject parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PimProject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PimProject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PimProject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PimProject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PimProject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PimProject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static PimProject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static PimProject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PimProject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PimProject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PimProject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.elca.vn.proto.model.PimProject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.elca.vn.proto.model.PimProject)
          PimProjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProjectProto.internal_static_com_elca_vn_model_PimProject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProjectProto.internal_static_com_elca_vn_model_PimProject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PimProject.class, PimProject.Builder.class);
    }

    // Construct using com.elca.vn.proto.model.PimProject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      projectNumber_ = 0;

      projectName_ = "";

      customer_ = "";

      groupID_ = 0L;

      memberVISAs_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;

      if (startDateBuilder_ == null) {
        startDate_ = null;
      } else {
        startDate_ = null;
        startDateBuilder_ = null;
      }
      if (endDateBuilder_ == null) {
        endDate_ = null;
      } else {
        endDate_ = null;
        endDateBuilder_ = null;
      }
      processingStatus_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProjectProto.internal_static_com_elca_vn_model_PimProject_descriptor;
    }

    @java.lang.Override
    public PimProject getDefaultInstanceForType() {
      return PimProject.getDefaultInstance();
    }

    @java.lang.Override
    public PimProject build() {
      PimProject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public PimProject buildPartial() {
      PimProject result = new PimProject(this);
      int from_bitField0_ = bitField0_;
      result.projectNumber_ = projectNumber_;
      result.projectName_ = projectName_;
      result.customer_ = customer_;
      result.groupID_ = groupID_;
      if (((bitField0_ & 0x00000001) != 0)) {
        memberVISAs_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.memberVISAs_ = memberVISAs_;
      result.status_ = status_;
      if (startDateBuilder_ == null) {
        result.startDate_ = startDate_;
      } else {
        result.startDate_ = startDateBuilder_.build();
      }
      if (endDateBuilder_ == null) {
        result.endDate_ = endDate_;
      } else {
        result.endDate_ = endDateBuilder_.build();
      }
      result.processingStatus_ = processingStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PimProject) {
        return mergeFrom((PimProject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PimProject other) {
      if (other == PimProject.getDefaultInstance()) return this;
      if (other.getProjectNumber() != 0) {
        setProjectNumber(other.getProjectNumber());
      }
      if (!other.getProjectName().isEmpty()) {
        projectName_ = other.projectName_;
        onChanged();
      }
      if (!other.getCustomer().isEmpty()) {
        customer_ = other.customer_;
        onChanged();
      }
      if (other.getGroupID() != 0L) {
        setGroupID(other.getGroupID());
      }
      if (!other.memberVISAs_.isEmpty()) {
        if (memberVISAs_.isEmpty()) {
          memberVISAs_ = other.memberVISAs_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMemberVISAsIsMutable();
          memberVISAs_.addAll(other.memberVISAs_);
        }
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasStartDate()) {
        mergeStartDate(other.getStartDate());
      }
      if (other.hasEndDate()) {
        mergeEndDate(other.getEndDate());
      }
      if (other.processingStatus_ != 0) {
        setProcessingStatusValue(other.getProcessingStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      PimProject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (PimProject) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int projectNumber_ ;
    /**
     * <code>int32 projectNumber = 2;</code>
     * @return The projectNumber.
     */
    public int getProjectNumber() {
      return projectNumber_;
    }
    /**
     * <code>int32 projectNumber = 2;</code>
     * @param value The projectNumber to set.
     * @return This builder for chaining.
     */
    public Builder setProjectNumber(int value) {
      
      projectNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 projectNumber = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProjectNumber() {
      
      projectNumber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object projectName_ = "";
    /**
     * <code>string projectName = 3;</code>
     * @return The projectName.
     */
    public java.lang.String getProjectName() {
      java.lang.Object ref = projectName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string projectName = 3;</code>
     * @return The bytes for projectName.
     */
    public com.google.protobuf.ByteString
        getProjectNameBytes() {
      java.lang.Object ref = projectName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string projectName = 3;</code>
     * @param value The projectName to set.
     * @return This builder for chaining.
     */
    public Builder setProjectName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      projectName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string projectName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProjectName() {
      
      projectName_ = getDefaultInstance().getProjectName();
      onChanged();
      return this;
    }
    /**
     * <code>string projectName = 3;</code>
     * @param value The bytes for projectName to set.
     * @return This builder for chaining.
     */
    public Builder setProjectNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      projectName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object customer_ = "";
    /**
     * <code>string customer = 4;</code>
     * @return The customer.
     */
    public java.lang.String getCustomer() {
      java.lang.Object ref = customer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string customer = 4;</code>
     * @return The bytes for customer.
     */
    public com.google.protobuf.ByteString
        getCustomerBytes() {
      java.lang.Object ref = customer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customer = 4;</code>
     * @param value The customer to set.
     * @return This builder for chaining.
     */
    public Builder setCustomer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customer = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomer() {
      
      customer_ = getDefaultInstance().getCustomer();
      onChanged();
      return this;
    }
    /**
     * <code>string customer = 4;</code>
     * @param value The bytes for customer to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customer_ = value;
      onChanged();
      return this;
    }

    private long groupID_ ;
    /**
     * <code>int64 groupID = 5;</code>
     * @return The groupID.
     */
    public long getGroupID() {
      return groupID_;
    }
    /**
     * <code>int64 groupID = 5;</code>
     * @param value The groupID to set.
     * @return This builder for chaining.
     */
    public Builder setGroupID(long value) {
      
      groupID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 groupID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupID() {
      
      groupID_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList memberVISAs_ = emptyLongList();
    private void ensureMemberVISAsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        memberVISAs_ = mutableCopy(memberVISAs_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 memberVISAs = 6;</code>
     * @return A list containing the memberVISAs.
     */
    public java.util.List<java.lang.Long>
        getMemberVISAsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(memberVISAs_) : memberVISAs_;
    }
    /**
     * <code>repeated int64 memberVISAs = 6;</code>
     * @return The count of memberVISAs.
     */
    public int getMemberVISAsCount() {
      return memberVISAs_.size();
    }
    /**
     * <code>repeated int64 memberVISAs = 6;</code>
     * @param index The index of the element to return.
     * @return The memberVISAs at the given index.
     */
    public long getMemberVISAs(int index) {
      return memberVISAs_.getLong(index);
    }
    /**
     * <code>repeated int64 memberVISAs = 6;</code>
     * @param index The index to set the value at.
     * @param value The memberVISAs to set.
     * @return This builder for chaining.
     */
    public Builder setMemberVISAs(
        int index, long value) {
      ensureMemberVISAsIsMutable();
      memberVISAs_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 memberVISAs = 6;</code>
     * @param value The memberVISAs to add.
     * @return This builder for chaining.
     */
    public Builder addMemberVISAs(long value) {
      ensureMemberVISAsIsMutable();
      memberVISAs_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 memberVISAs = 6;</code>
     * @param values The memberVISAs to add.
     * @return This builder for chaining.
     */
    public Builder addAllMemberVISAs(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureMemberVISAsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, memberVISAs_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 memberVISAs = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemberVISAs() {
      memberVISAs_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.com.elca.vn.proto.model.Status status = 7;</code>
     * @return The enum numeric value on the wire for status.
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.elca.vn.proto.model.Status status = 7;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.elca.vn.proto.model.Status status = 7;</code>
     * @return The status.
     */
    public Status getStatus() {
      @SuppressWarnings("deprecation")
      Status result = Status.valueOf(status_);
      return result == null ? Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.elca.vn.proto.model.Status status = 7;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.elca.vn.proto.model.Status status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp startDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp startDate = 8;</code>
     * @return Whether the startDate field is set.
     */
    public boolean hasStartDate() {
      return startDateBuilder_ != null || startDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 8;</code>
     * @return The startDate.
     */
    public com.google.protobuf.Timestamp getStartDate() {
      if (startDateBuilder_ == null) {
        return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
      } else {
        return startDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 8;</code>
     */
    public Builder setStartDate(com.google.protobuf.Timestamp value) {
      if (startDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startDate_ = value;
        onChanged();
      } else {
        startDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 8;</code>
     */
    public Builder setStartDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (startDateBuilder_ == null) {
        startDate_ = builderForValue.build();
        onChanged();
      } else {
        startDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 8;</code>
     */
    public Builder mergeStartDate(com.google.protobuf.Timestamp value) {
      if (startDateBuilder_ == null) {
        if (startDate_ != null) {
          startDate_ =
            com.google.protobuf.Timestamp.newBuilder(startDate_).mergeFrom(value).buildPartial();
        } else {
          startDate_ = value;
        }
        onChanged();
      } else {
        startDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 8;</code>
     */
    public Builder clearStartDate() {
      if (startDateBuilder_ == null) {
        startDate_ = null;
        onChanged();
      } else {
        startDate_ = null;
        startDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 8;</code>
     */
    public com.google.protobuf.Timestamp.Builder getStartDateBuilder() {
      
      onChanged();
      return getStartDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
      if (startDateBuilder_ != null) {
        return startDateBuilder_.getMessageOrBuilder();
      } else {
        return startDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getStartDateFieldBuilder() {
      if (startDateBuilder_ == null) {
        startDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getStartDate(),
                getParentForChildren(),
                isClean());
        startDate_ = null;
      }
      return startDateBuilder_;
    }

    private com.google.protobuf.Timestamp endDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> endDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp endDate = 9;</code>
     * @return Whether the endDate field is set.
     */
    public boolean hasEndDate() {
      return endDateBuilder_ != null || endDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 9;</code>
     * @return The endDate.
     */
    public com.google.protobuf.Timestamp getEndDate() {
      if (endDateBuilder_ == null) {
        return endDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
      } else {
        return endDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 9;</code>
     */
    public Builder setEndDate(com.google.protobuf.Timestamp value) {
      if (endDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endDate_ = value;
        onChanged();
      } else {
        endDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 9;</code>
     */
    public Builder setEndDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (endDateBuilder_ == null) {
        endDate_ = builderForValue.build();
        onChanged();
      } else {
        endDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 9;</code>
     */
    public Builder mergeEndDate(com.google.protobuf.Timestamp value) {
      if (endDateBuilder_ == null) {
        if (endDate_ != null) {
          endDate_ =
            com.google.protobuf.Timestamp.newBuilder(endDate_).mergeFrom(value).buildPartial();
        } else {
          endDate_ = value;
        }
        onChanged();
      } else {
        endDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 9;</code>
     */
    public Builder clearEndDate() {
      if (endDateBuilder_ == null) {
        endDate_ = null;
        onChanged();
      } else {
        endDate_ = null;
        endDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 9;</code>
     */
    public com.google.protobuf.Timestamp.Builder getEndDateBuilder() {
      
      onChanged();
      return getEndDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder() {
      if (endDateBuilder_ != null) {
        return endDateBuilder_.getMessageOrBuilder();
      } else {
        return endDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getEndDateFieldBuilder() {
      if (endDateBuilder_ == null) {
        endDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getEndDate(),
                getParentForChildren(),
                isClean());
        endDate_ = null;
      }
      return endDateBuilder_;
    }

    private int processingStatus_ = 0;
    /**
     * <code>.com.elca.vn.proto.model.ProcessingStatus processingStatus = 10;</code>
     * @return The enum numeric value on the wire for processingStatus.
     */
    public int getProcessingStatusValue() {
      return processingStatus_;
    }
    /**
     * <code>.com.elca.vn.proto.model.ProcessingStatus processingStatus = 10;</code>
     * @param value The enum numeric value on the wire for processingStatus to set.
     * @return This builder for chaining.
     */
    public Builder setProcessingStatusValue(int value) {
      processingStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.elca.vn.proto.model.ProcessingStatus processingStatus = 10;</code>
     * @return The processingStatus.
     */
    public ProcessingStatus getProcessingStatus() {
      @SuppressWarnings("deprecation")
      ProcessingStatus result = ProcessingStatus.valueOf(processingStatus_);
      return result == null ? ProcessingStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.elca.vn.proto.model.ProcessingStatus processingStatus = 10;</code>
     * @param value The processingStatus to set.
     * @return This builder for chaining.
     */
    public Builder setProcessingStatus(ProcessingStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      processingStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.elca.vn.proto.model.ProcessingStatus processingStatus = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessingStatus() {
      
      processingStatus_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.elca.vn.proto.model.PimProject)
  }

  // @@protoc_insertion_point(class_scope:com.elca.vn.proto.model.PimProject)
  private static final PimProject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PimProject();
  }

  public static PimProject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PimProject>
      PARSER = new com.google.protobuf.AbstractParser<PimProject>() {
    @java.lang.Override
    public PimProject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PimProject(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PimProject> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PimProject> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public PimProject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

