// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pim_project.proto

package com.elca.vn.proto.model;

/**
 * Protobuf enum {@code com.elca.vn.proto.model.ProcessingStatus}
 */
public enum ProcessingStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>INSERT = 0;</code>
   */
  INSERT(0),
  /**
   * <code>UPDATE = 1;</code>
   */
  UPDATE(1),
  /**
   * <code>DELETE = 2;</code>
   */
  DELETE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>INSERT = 0;</code>
   */
  public static final int INSERT_VALUE = 0;
  /**
   * <code>UPDATE = 1;</code>
   */
  public static final int UPDATE_VALUE = 1;
  /**
   * <code>DELETE = 2;</code>
   */
  public static final int DELETE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProcessingStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ProcessingStatus forNumber(int value) {
    switch (value) {
      case 0: return INSERT;
      case 1: return UPDATE;
      case 2: return DELETE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProcessingStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProcessingStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProcessingStatus>() {
          public ProcessingStatus findValueByNumber(int number) {
            return ProcessingStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ProjectProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ProcessingStatus[] VALUES = values();

  public static ProcessingStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProcessingStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.elca.vn.proto.model.ProcessingStatus)
}

