// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_project_service.proto

package com.elca.vn.proto;

import com.elca.vn.proto.model.ProjectProto;

public final class BaseProjectServiceProto {
  private BaseProjectServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032base_project_service.proto\022\023com.elca.v" +
      "n.service\032\021pim_project.proto2\271\001\n\022BasePro" +
      "jectService\022R\n\020insertNewProject\022\035.com.el" +
      "ca.vn.model.PimProject\032\035.com.elca.vn.mod" +
      "el.PimProject\"\000\022O\n\rupdateProject\022\035.com.e" +
      "lca.vn.model.PimProject\032\035.com.elca.vn.mo" +
      "del.PimProject\"\000B!B\027BaseProjectServicePr" +
      "otoP\001\242\002\003RTGb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ProjectProto.getDescriptor(),
        });
    ProjectProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
